DealSe/Areas/Admin/ViewModels/EmailTemplateViewModel.cs
namespace DealSe.Areas.Admin.ViewModels
{
    public class EmailTemplateViewModel
    {
        public int EmailTemplateId { get; set; }
        public string EmailTemplateName { get; set; }
        public string EmailTemplateSubject { get; set; }
        public string EmailTemplateBody { get; set; }
        public string AddedDate { get; set; }
        public string UpdatedDate { get; set; }
    }
}

DealSe/Areas/Admin/Controllers/EmailTemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DealSe.ActionFilter;
using DealSe.Areas.Admin.FormModels;
using DealSe.Areas.Admin.ViewModels;
using DealSe.Domain.Models;
using DealSe.Service.Common;
using DealSe.Service.Interface;
using DealSe.Utils;
using Microsoft.AspNetCore.Mvc;

namespace DealSe.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AdminAuthorizeFilter]
    public class EmailTemplateController : Controller
    {
        private readonly IEmailTemplateService emailTemplateService;
        private readonly IMapper mapper;
        public EmailTemplateController(IEmailTemplateService emailTemplateService, IMapper mapper)
        {
            this.emailTemplateService = emailTemplateService;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult LoadData(DTParameters param)
        {
            DTResult<EmailTemplateViewModel> finalResult = new DTResult<EmailTemplateViewModel>();
            int start = Convert.ToInt32(param.Start);
            int pagesize = Convert.ToInt32(param.Length);
            string sortOrder = param.SortOrder;
            var result = emailTemplateService.GetAll().OrderByDescending(a => a.AddedDate);
            var fResult = mapper.Map<IEnumerable<EmailTemplate>, IEnumerable<EmailTemplateViewModel>>(result);
            if (!string.IsNullOrEmpty(param.Search.Value))
            {
                var searchvalue = param.Search.Value.ToLower().Trim();
                var columnsSearchValue = param.Columns.Where(a => a.Name != "" && a.Searchable == false && a.Name != null).Select(a => a.Name.ToLower()).ToArray();
                fResult = fResult.AsQueryable().FullTextSearch(searchvalue, columnsSearchValue);
            }
            int filterCount = 0;
            filterCount = fResult.Count();
            fResult = fResult.Skip(start).Take(pagesize);
            fResult = ApplySorting(param, fResult);
            finalResult = new DTResult<EmailTemplateViewModel>
            {
                draw = param.Draw,
                data = fResult.ToList(),
                recordsFiltered = filterCount,
                recordsTotal = result.Count()
            };
            return Json(finalResult);
        }
        private static IEnumerable<EmailTemplateViewModel> ApplySorting(DTParameters param, IEnumerable<EmailTemplateViewModel> mappingResult)
        {
            if (param.Order != null)
            {
                var paramOrderdetails = param.Order.FirstOrDefault();
                if (paramOrderdetails.Column == 1)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.EmailTemplateName);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.EmailTemplateName);
                }
                else if (paramOrderdetails.Column == 2)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.EmailTemplateSubject);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.EmailTemplateSubject);
                }
                else if (paramOrderdetails.Column == 3)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.AddedDate);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.AddedDate);
                }
            }
            return mappingResult;
        }
        public IActionResult AddEmailTemplate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddEmailTemplate(EmailTemplateFormModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var checkExist = await emailTemplateService.CheckEmailTemplateExists(model.EmailTemplateName,0);
                    if (checkExist != null)
                    {
                        var message = DealSeResource.RecordExists;
                        ViewBag.Error = message.Replace("{0}", model.EmailTemplateName);
                        return View("AddEmailTemplate", model);
                    }
                    var mappedResult = mapper.Map<EmailTemplateFormModel, EmailTemplate>(model);
                    mappedResult.AddedDate = DateTime.Now;
                    await emailTemplateService.Create(mappedResult);
                    TempData["Success"] = DealSeResource.InsertMessage;
                    return RedirectToAction("Index");
                }
                return View("AddEmailTemplate", model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.InnerException.Message.ToString();
                return RedirectToAction("Index");
            }
        }
        public async Task<IActionResult> EditEmailTemplate(int id)
        {
            var emailTemplateResult = await emailTemplateService.GetById(id);
            if(emailTemplateResult != null)
            {
                var mappedResult = mapper.Map<EmailTemplate, EmailTemplateFormModel>(emailTemplateResult);
                return View(mappedResult);
            }
            TempData["Error"] = DealSeResource.NoRecordFound;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditEmailTemplate(EmailTemplateFormModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var checkExist = await emailTemplateService.CheckEmailTemplateExists(model.EmailTemplateName, model.EmailTemplateId);
                    if (checkExist != null)
                    {
                        var message = DealSeResource.RecordExists;
                        ViewBag.Error = message.Replace("{0}", model.EmailTemplateName);
                        return View("EditEmailTemplate", model);
                    }
                    var mappedResult = mapper.Map<EmailTemplateFormModel, EmailTemplate>(model);
                    mappedResult.UpdatedDate = DateTime.Now;
                    await emailTemplateService.Update(mappedResult);
                    TempData["Success"] = DealSeResource.UpdateMessage;
                    return RedirectToAction("Index");
                }
                return View("EditEmailTemplate", model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.InnerException.Message.ToString();
                return RedirectToAction("Index");
            }
        }

    }
}

DealSe/Areas/Admin/Views/EmailTemplate/AddEmailTemplate.cshtml
@*View to add email template*@
@model DealSe.Areas.Admin.FormModels.EmailTemplateFormModel
@{
	ViewData["Title"] = "AddEmailTemplate";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<ol class="breadcrumb">
	<li>
		<a href="@Url.Action("Index", "Home" , new {Area="Admin" })"><i class="entypo-home"></i>Home</a>
	</li>
	<li>
		<i class="entypo-cog"></i>Others
	</li>
	<li><a href="@Url.Action("Index", "EmailTemplate" , new { Area="Admin" })"><i class="entypo-mail"></i>Email Templates</a></li>
	<li class="active">
		<strong>Add Email Template</strong>
	</li>
</ol>
<h2>Add Email Template</h2>
<br />
@if (ViewBag.Error != null)
{
	<div class="row">
		<div class="col-md-12">

			<div class="alert alert-danger"><strong>Oops!</strong> @ViewBag.Error</div>
		</div>
	</div>
}
@using (Html.BeginForm("AddEmailTemplate", "EmailTemplate", FormMethod.Post))
{
	@Html.ValidationSummary(true);

			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label class="control-label" for="email_template_name">Email Name</label>
						<label class="field-validation-error">*</label>
						@Html.TextBoxFor(model => model.EmailTemplateName, new { @class = "form-control htmlvalid trimmed", @maxlength = "50" })
						<span id="errormsgForEmailTemplateName"></span>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label class="control-label" for="email_template_name">Email Subject</label>
						<label class="field-validation-error">*</label>
						@Html.TextBoxFor(model => model.EmailTemplateSubject, new { @class = "form-control htmlvalid trimmed", @maxlength = "100" })
						<span id="errormsgForEmailTemplateSubject"></span>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
						<label class="control-label" for="plan_url">Email Body</label>
						<label class="field-validation-error">*</label>
						@Html.TextAreaFor(model => model.EmailTemplateBody, new { id = "textarea1" })
						<span id="errormsgForEmailbody"></span>
					</div>
				</div>
			</div>
		<div class="row center">
			<button type="submit" id="btnsubmit" class="btn btn-success">
				<i class="glyphicon glyphicon-save"></i>
				Save
			</button>
			<a href="@Url.Action("Index", "EmailTemplate", new { Area = "Admin" })" class="btn btn-default">
				<i class="glyphicon glyphicon-remove"></i>
				Cancel
			</a>
		</div>
}
<script src="~/Admin/assets/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
	$(function () {
		tinymce.init({
			selector: '#textarea1',
			relative_urls: false,
			extended_valid_elements: "a[class|name|href|target|title|onclick|rel|style],style[language|type|src],script[language|type|src],iframe[src|style|width|height|scrolling|marginwidth|marginheight|frameborder],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name|style],head,html,body",
			width: 'auto',
			height: 'auto',
			plugins: [
				"advlist autolink link image lists charmap print preview hr anchor pagebreak",
				"searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking",
				"table contextmenu directionality emoticons paste textcolor code fullpage"
			],
			toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
			toolbar2: "| link unlink anchor | image media | forecolor backcolor  | print preview code ",
			image_advtab: true,
			file_browser_callback: function (field_name, url, type, win) {
				var w = window,
					d = document,
					e = d.documentElement,
					g = d.getElementsByTagName('body')[0],
					x = w.innerWidth || e.clientWidth || g.clientWidth,
					y = w.innerHeight || e.clientHeight || g.clientHeight;

				var cmsURL = '/mcemanager/index.html?&field_name=' + field_name + '&langCode=' + tinymce.settings.language;

				if (type == 'image') {
					cmsURL = cmsURL + "&type=images";
				}

				tinyMCE.activeEditor.windowManager.open({
					file: cmsURL,
					title: 'Filemanager',
					width: x * 0.9,
					height: y * 0.9,
					resizable: "yes",
					close_previous: "no"
				});
			}
		});
	});
	$("#btnsubmit").click(function () {
		var valid = true;
		var emailTemplateName = $("#EmailTemplateName").val();
		var emailTemplateSubject = $("#EmailTemplateSubject").val();
		var emailBody = tinymce.get('textarea1').getBody().textContent;
		if (emailTemplateName == "" || emailTemplateName == null) {
			$("#errormsgForEmailTemplateName")[0].innerHTML = "Email Name is required";
			$("#errormsgForEmailTemplateName")[0].style.color = "red";
			valid = false;
		}
		else {
			$("#errormsgForEmailTemplateName")[0].innerHTML = " ";
		}
		if (emailTemplateSubject == "" || emailTemplateSubject == null) {
			$("#errormsgForEmailTemplateSubject")[0].innerHTML = "Email Subject is required";
			$("#errormsgForEmailTemplateSubject")[0].style.color = "red";
			valid = false;
		}
		else {
			$("#errormsgForEmailTemplateSubject")[0].innerHTML = " ";
		}
		if (emailBody == "" || emailBody == null) {
			$("#errormsgForEmailbody")[0].innerHTML = "Email Body is required";
			$("#errormsgForEmailbody")[0].style.color = "red";
			valid = false;
		}
		else {
			$("#errormsgForEmailbody")[0].innerHTML = " ";
		}
		if (valid == false) {
			return false;
		}
	});
</script>

DealSe/Areas/Admin/Views/EmailTemplate/EditEmailTemplate.cshtml
@*View to edit email template*@
@model DealSe.Areas.Admin.FormModels.EmailTemplateFormModel
@{
	ViewData["Title"] = "EditEmailTemplate";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<ol class="breadcrumb">
	<li>
		<a href="@Url.Action("Index", "Home" , new {Area="Admin" })"><i class="entypo-home"></i>Home</a>
	</li>
	<li>
		<i class="entypo-cog"></i>Others
	</li>
	<li><a href="@Url.Action("Index", "EmailTemplate" , new { Area="Admin" })"><i class="entypo-mail"></i>Email Templates</a></li>
	<li class="active">
		<strong>Edit Email Template</strong>
	</li>
</ol>
<h2>Edit Email Template</h2>
<br />
@if (ViewBag.Error != null)
{
	<div class="row">
		<div class="col-md-12">

			<div class="alert alert-danger"><strong>Oops!</strong> @ViewBag.Error</div>
		</div>
	</div>
}
@using (Html.BeginForm("EditEmailTemplate", "EmailTemplate", FormMethod.Post))
{
	@Html.ValidationSummary(true);
	@Html.HiddenFor(model => model.EmailTemplateId)
	@Html.HiddenFor(model => model.AddedDate)
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label class="control-label" for="email_template_name">Email Name</label>
						<label class="field-validation-error">*</label>
						@Html.TextBoxFor(model => model.EmailTemplateName, new { @class = "form-control htmlvalid trimmed", @maxlength = "50" })
						<span id="errormsgForEmailTemplateName"></span>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label class="control-label" for="email_template_name">Email Subject</label>
						<label class="field-validation-error">*</label>
						@Html.TextBoxFor(model => model.EmailTemplateSubject, new { @class = "form-control htmlvalid trimmed", @maxlength = "100" })
						<span id="errormsgForEmailTemplateSubject"></span>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
						<label class="control-label" for="plan_url">Email Body</label>
						<label class="field-validation-error">*</label>
						@Html.TextAreaFor(model => model.EmailTemplateBody, new { id = "textarea1" })
						<span id="errormsgForEmailbody"></span>
					</div>
				</div>
			</div>
		<div class="row center">
			<button type="submit" id="btnsubmit" class="btn btn-success">
				<i class="glyphicon glyphicon-save"></i>
				Save
			</button>
			<a href="@Url.Action("Index", "EmailTemplate", new { Area = "Admin" })" class="btn btn-default">
				<i class="glyphicon glyphicon-remove"></i>
				Cancel
			</a>
		</div>
}
<script src="~/Admin/assets/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
	$(function () {
		tinymce.init({
			selector: '#textarea1',
			relative_urls: false,
			extended_valid_elements: "a[class|name|href|target|title|onclick|rel|style],style[language|type|src],script[language|type|src],iframe[src|style|width|height|scrolling|marginwidth|marginheight|frameborder],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name|style],head,html,body",
			width: 'auto',
			height: 'auto',
			plugins: [
				"advlist autolink link image lists charmap print preview hr anchor pagebreak",
				"searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking",
				"table contextmenu directionality emoticons paste textcolor code fullpage"
			],
			toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
			toolbar2: "| link unlink anchor | image media | forecolor backcolor  | print preview code ",
			image_advtab: true,
			file_browser_callback: function (field_name, url, type, win) {
				var w = window,
					d = document,
					e = d.documentElement,
					g = d.getElementsByTagName('body')[0],
					x = w.innerWidth || e.clientWidth || g.clientWidth,
					y = w.innerHeight || e.clientHeight || g.clientHeight;

				var cmsURL = '/mcemanager/index.html?&field_name=' + field_name + '&langCode=' + tinymce.settings.language;

				if (type == 'image') {
					cmsURL = cmsURL + "&type=images";
				}

				tinyMCE.activeEditor.windowManager.open({
					file: cmsURL,
					title: 'Filemanager',
					width: x * 0.9,
					height: y * 0.9,
					resizable: "yes",
					close_previous: "no"
				});
			}
		});
	});
	$("#btnsubmit").click(function () {
		var valid = true;
		var emailTemplateName = $("#EmailTemplateName").val();
		var emailTemplateSubject = $("#EmailTemplateSubject").val();
		var emailBody = tinymce.get('textarea1').getBody().textContent;
		if (emailTemplateName == "" || emailTemplateName == null) {
			$("#errormsgForEmailTemplateName")[0].innerHTML = "Email Name is required";
			$("#errormsgForEmailTemplateName")[0].style.color = "red";
			valid = false;
		}
		if (emailTemplateSubject == "" || emailTemplateSubject == null) {
			$("#errormsgForEmailTemplateSubject")[0].innerHTML = "Email Subject is required";
			$("#errormsgForEmailTemplateSubject")[0].style.color = "red";
			valid = false;
		}
		if (emailBody == "" || emailBody == null) {
			$("#errormsgForEmailbody")[0].innerHTML = "Email Body is required";
			$("#errormsgForEmailbody")[0].style.color = "red";
			valid = false;
		}
		if (valid == false) {
			return false;
		}
	});
</script>

DealSe/Areas/Admin/Views/EmailTemplate/Index.cshtml
@*View to show email template details*@
@model DealSe.Areas.Admin.ViewModels.EmailTemplateViewModel
@{
	ViewData["Title"] = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<ol class="breadcrumb">
    <li>
        <a href="@Url.Action("Index", "Home",new { Area = "Admin" })"><i class="entypo-home"></i>Home</a>
    </li>
    <li>
        <i class="entypo-cog"></i>Others
    </li>
    <li class="active">
        <strong><i class="entypo-mail"></i>Email Template</strong>
    </li>
</ol>
<h2>Email Template</h2>
<br />
@if (TempData["Error"] != null)
{
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger"><strong>Oops!</strong><br /><span> @TempData["Error"]</span></div>
    </div>
</div>
}
else if (TempData["Success"] != null)
{
<div class="row">
    <div class="col-md-14">
        <div class="alert alert-success"><strong>Success!</strong> @TempData["Success"]</div>
    </div>
</div>
}
<br class="clear" />
@await Html.PartialAsync("_EmailTemplateDetails")
@await Html.PartialAsync("_DatatableCSSJSView")
<script src="~/admin/assets/js/tinymce.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        loadData();
    });
    var responsiveHelper;
    var breakpointDefinition = {
        tablet: 1024,
        phone: 480
    };
    function loadData() {
        var tableContainer;
        tableContainer = $("#EmailTemplatedetails");
        tableContainer.dataTable(
            {
                "destroy": true,
                "aaSorting": [],
                "pageLength": 10,
                "bStateSave": false,
                "processing": true,
                oLanguage: {
                    sProcessing: "<div id=preloader></div>"
                },
                "serverSide": true,
                "ajax": {
                    "url": '/Admin/EmailTemplate/LoadData',
                    "type": "POST",
                    "datatype": "json"
                },

                "aoColumns": [
                    { "data": "emailTemplateName", "name": "emailTemplateName", "bSearchable": true, "autoWidth": true, "width": "20%" },
                    { "data": "emailTemplateSubject", "name": "emailTemplateSubject", "bSearchable": true, "autoWidth": true, "width": "15%" },
                    { "data": "addedDate", "name": "addedDate", "bSearchable": true, "autoWidth": true, "width": "15%" },

                    {
                        "mData": "Activated", "bSearchable": false, "bSortable": false, "autoWidth": true, "width": "10%",
                        "mRender": function (data, type, row) {
                            return '<a class="btn btn-blue btn-sm btn-icon icon-left" href="/Admin/EmailTemplate/EditEmailTemplate/' + row.emailTemplateId + '"><i class="entypo-pencil"></i>Edit</a>';
                        }, "sClass": "view-more"
                    }
                ],
                bAutoWidth: false,
                fnPreDrawCallback: function () {
                    if (!responsiveHelper) {
                        responsiveHelper = new ResponsiveDatatablesHelper(tableContainer, breakpointDefinition);
                    }
                },
                fnRowCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    responsiveHelper.createExpandIcon(nRow);
                },
                fnDrawCallback: function (oSettings) {
                    responsiveHelper.respond();
                    responsivePaginationDesign();
                    if (window.matchMedia('(max-width: 768px)').matches) {
                        responsiveTableColumn("#EmailTemplatedetails");
                    }
                }
            });
        $(".dataTables_wrapper select").select2({
            minimumResultsForSearch: -1
        });
    }
    $(window).resize(function () {
        if (window.matchMedia('(max-width: 768px)').matches) {
            responsiveTableColumn('#EmailTemplatedetails');
        }
    })
</script>

DealSe/Areas/Admin/Views/EmailTemplate/_EmailTemplateDetails.cshtml
@*Partial view to show email template details*@
<table class="table table-bordered table-striped datatable scroll" id="EmailTemplatedetails">
    <thead>
        <tr>
            <th>Email Template</th>
            <th>Email Subject</th>
            <th>Added Date</th>
            <th class="actionedit view-more">
                Actions
            </th>
        </tr>
    </thead>
</table>