DealSe/Areas/Admin/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DealSe.Areas.Admin.FormModels;
using DealSe.Areas.Admin.ViewModels;
using DealSe.Domain.Models;
using DealSe.Domain.SPModel;
using DealSe.Service.Common;
using DealSe.Service.Interface;
using DealSe.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using DealSe.ActionFilter;
using DealSe.Common;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DealSe.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AdminAuthorizeFilter]
    public class AreaController : Controller
    {
        private readonly DealSeContext dataContext;
        private readonly ICountryService countryService;
        private readonly IStateService stateService;
        private readonly ICityService cityService;
        private readonly IAreaService areaService;
        private readonly IMapper mapper;

        public AreaController(DealSeContext dataContext, IMapper mapper, IAreaService areaService, ICountryService countryService, IStateService stateService, ICityService cityService)
        {
            this.dataContext = dataContext;
            this.countryService = countryService;
            this.stateService = stateService;
            this.cityService = cityService;
            this.areaService = areaService;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            AreaViewModel AreaViewModel = new AreaViewModel();
            AreaViewModel.CountryId = Convert.ToInt32(TempData["CountryId"]);
            AreaViewModel.StateId = Convert.ToInt32(TempData["StateId"]);
            AreaViewModel.CityId = Convert.ToInt32(TempData["CityId"]);
            ViewBag.CountryList = FillDropdownList.FillCountryList(countryService);
            ViewBag.StateList = FillDropdownList.FillStateList(stateService, AreaViewModel.CountryId);
            ViewBag.CityList = FillDropdownList.FillCityList(cityService, AreaViewModel.StateId);
            return View(AreaViewModel);
        }

        //Method for load data on listing page from database
        [HttpPost]
        public JsonResult LoadData(DTParameters param,int cityId)
        {
            try
            {
                DTResult<AreaViewModel> finalResult = new DTResult<AreaViewModel>();
                int start = Convert.ToInt32(param.Start);
                int pagesize = Convert.ToInt32(param.Length);
                //Get filtered product list
                SqlParameter[] parameters = new SqlParameter[1];
                parameters[0] = new SqlParameter("@CityId", cityId);

                var result = dataContext.GetAllArea.FromSqlRaw("GetAllAreaForAdminListing @CityId", parameters).ToList();
                var mappedResult = mapper.Map<IEnumerable<GetAllAreaSPModel>, IEnumerable<AreaViewModel>>(result);
                if (!string.IsNullOrEmpty(param.Search.Value))
                {
                    var searchvalue = param.Search.Value.ToLower().Trim();
                    var columnsSearchValue = param.Columns.Where(a => a.Name != "" && a.Searchable == false && a.Name != null).Select(a => a.Name.ToLower()).ToArray();
                    mappedResult = mappedResult.AsQueryable().FullTextSearch(searchvalue, columnsSearchValue);
                }
                int filterCount = mappedResult.Count();
                mappedResult = mappedResult.Skip(start).Take(pagesize);
                mappedResult = ApplySorting(param, mappedResult);
                finalResult = new DTResult<AreaViewModel>
                {
                    draw = param.Draw,
                    data = mappedResult.ToList(),
                    recordsFiltered = filterCount,
                    recordsTotal = result.Count()
                };
                return Json(finalResult);
            }
            catch (Exception ex)
            {
                return Json(ex);
                throw;
            }
            
        }

        //Method for apply sorting
        private static IEnumerable<AreaViewModel> ApplySorting(DTParameters param, IEnumerable<AreaViewModel> mappingResult)
        {
            if (param.Order != null)
            {
                var paramOrderdetails = param.Order.FirstOrDefault();
                if (paramOrderdetails.Column == 2)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.Name);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.Name);
                }
                else if (paramOrderdetails.Column == 3)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.AddedDate);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.AddedDate);
                }
                else if (paramOrderdetails.Column == 4)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.Active);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.Active);
                }
            }
            return mappingResult;
        }

        //Get method of add Area
        public IActionResult AddArea()
        {
            AreaFormModel model = new AreaFormModel();
            model.Active = true;
            ViewBag.CountryList = FillDropdownList.FillCountryList(countryService);
            ViewBag.StateList = new List<SelectListItem>();
            ViewBag.CityList = new List<SelectListItem>();
            return View(model);
        }

        //Post method of add Area
        [HttpPost]
        public async Task<IActionResult> AddArea(AreaFormModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var checkExist = await areaService.CheckAreaExists(0, model.Name, model.CityId);
                    if (checkExist != null)
                    {
                        var message = DealSeResource.RecordExists;
                        ViewBag.Error = message.Replace("{0}", model.Name);
                        ViewBag.CountryList = FillDropdownList.FillCountryList(countryService);
                        ViewBag.StateList = FillDropdownList.FillStateList(stateService, model.CountryId);
                        ViewBag.CityList = FillDropdownList.FillCityList(cityService, model.StateId);
                        return View(model);
                    }
                    var mappedResult = mapper.Map<AreaFormModel, Area>(model);
                    mappedResult.AddedDate = DateTime.Now;
                    await areaService.Create(mappedResult);
                    TempData["Success"] = DealSeResource.InsertMessage;
                    TempData["CountryId"] = model.CountryId;
                    TempData["StateId"] = model.StateId;
                    TempData["CityId"] = model.CityId;
                    return RedirectToAction("Index");
                }
                ViewBag.Error = DealSeResource.InternalServerError;
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.InnerException != null ? ex.InnerException.Message.ToString() : ex.Message.ToString();
                return RedirectToAction("Index");
            }
        }

        //Get method of edit Area
        public async Task<IActionResult> EditArea(int id)
        {
            var Area = await areaService.GetById(id);
            if (Area != null)
            {
                ViewBag.CountryList = FillDropdownList.FillCountryList(countryService);
                ViewBag.StateList = FillDropdownList.FillStateList(stateService, Area.City.State.CountryId);
                ViewBag.CityList = FillDropdownList.FillCityList(cityService, Area.City.StateId);
                var mappedResult = mapper.Map<Area, AreaFormModel>(Area);
                mappedResult.CountryId = Area.City.State.CountryId;
                mappedResult.StateId = Area.City.State.StateId;
                mappedResult.CityId = Area.City.CityId;
                return View(mappedResult);
            }
            TempData["Error"] = DealSeResource.NoRecordFound;
            return RedirectToAction("Index");
        }

        //Post method of edit Area
        [HttpPost]
        public async Task<IActionResult> EditArea(AreaFormModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var checkExist = await areaService.CheckAreaExists(model.AreaId, model.Name,model.StateId);
                    if (checkExist != null)
                    {
                        var message = DealSeResource.RecordExists;
                        ViewBag.Error = message.Replace("{0}", model.Name);
                        ViewBag.CountryList = FillDropdownList.FillCountryList(countryService);
                        ViewBag.StateList = FillDropdownList.FillStateList(stateService, model.CountryId);
                        ViewBag.CityList = FillDropdownList.FillCityList(cityService, model.StateId);
                        return View(model);
                    }
                    var mappedResult = mapper.Map<AreaFormModel, Area>(model);
                    mappedResult.UpdatedDate = DateTime.Now;
                    await areaService.Update(mappedResult);
                    TempData["Success"] = DealSeResource.UpdateMessage;
                    TempData["CountryId"] = model.CountryId;
                    TempData["StateId"] = model.StateId;
                    TempData["CityId"] = model.CityId;
                    return RedirectToAction("Index");

DealSe/Areas/Admin/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using DealSe.ActionFilter;
using DealSe.Areas.Admin.ViewModels;
using DealSe.Domain.Models;
using DealSe.Domain.SPModel;
using DealSe.Service.Common;
using DealSe.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DealSe.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AdminAuthorizeFilter]
    public class OfferController : Controller
    {
        private readonly IOfferService offerService;
        private readonly DealSeContext dataContext;
        private readonly IMapper mapper;
        public OfferController(IOfferService offerService, DealSeContext dataContext, IMapper mapper)
        {
            this.offerService = offerService;
            this.dataContext = dataContext;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        //Method for load data on listing page from database
        [HttpPost]
        public JsonResult LoadData(DTParameters param)
        {
            try
            {
                DTResult<OfferViewModel> finalResult = new DTResult<OfferViewModel>();
                int start = Convert.ToInt32(param.Start);
                int pagesize = Convert.ToInt32(param.Length);
                var result = dataContext.GetAllOffers.FromSqlRaw("GetAllOffers").ToList();
                var mappedResult = mapper.Map<IEnumerable<GetAllOffersSPModel>, IEnumerable<OfferViewModel>>(result);
                if (!string.IsNullOrEmpty(param.Search.Value))
                {
                    var searchvalue = param.Search.Value.ToLower().Trim();
                    var columnsSearchValue = param.Columns.Where(a => a.Name != "" && a.Searchable == false && a.Name != null).Select(a => a.Name.ToLower()).ToArray();
                    mappedResult = mappedResult.AsQueryable().FullTextSearch(searchvalue, columnsSearchValue);
                }
                int filterCount = mappedResult.Count();
                mappedResult = mappedResult.Skip(start).Take(pagesize);
                mappedResult = ApplySorting(param, mappedResult);
                finalResult = new DTResult<OfferViewModel>
                {
                    draw = param.Draw,
                    data = mappedResult.ToList(),
                    recordsFiltered = filterCount,
                    recordsTotal = result.Count()
                };
                return Json(finalResult);
            }
            catch (Exception ex)
            {
                return Json(ex);
                throw;
            }

        }

        //Method for apply sorting
        private static IEnumerable<OfferViewModel> ApplySorting(DTParameters param, IEnumerable<OfferViewModel> mappingResult)
        {
            if (param.Order != null)
            {
                var paramOrderdetails = param.Order.FirstOrDefault();
                if (paramOrderdetails.Column == 2)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.StoreName);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.StoreName);
                }
                else if (paramOrderdetails.Column == 3)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.Name);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.Name);
                }
                else if (paramOrderdetails.Column == 4)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.ValidityDates);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.ValidityDates);
                }
                else if (paramOrderdetails.Column == 5)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.AddedDate);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.AddedDate);
                }
                else if (paramOrderdetails.Column == 6)
                {
                    if (paramOrderdetails.Dir == DTOrderDir.ASC)
                        mappingResult = mappingResult.OrderBy(top => top.UserRedeemLimit);
                    else
                        mappingResult = mappingResult.OrderByDescending(top => top.UserRedeemLimit);
                }
            }
            return mappingResult;
        }

        [HttpGet]
        public IActionResult AddOffer()
        {
            return View();
        }
    }
}

DealSe/Areas/Admin/Views/Shared/_CommonDateCssJSView.cshtml
<link href="~/Admin/assets/css/daterangepicker-bs3.css" rel="stylesheet" />
<script src="~/Admin/assets/js/moment.min.js"></script>
<script src="~/Admin/assets/js/bootstrap-timepicker.min.js"></script>
<script src="~/Admin/assets/js/bootstrap-datepicker.js"></script>
<script src="~/Admin/assets/js/bootstrap-colorpicker.min.js"></script>
<script src="~/Admin/assets/js/daterangepicker.js"></script>

DealSe/Areas/Admin/Views/Shared/_CommonDateRangeCssJSView.cshtml
<link href="~/Admin/assets/css/daterangepicker-bs3.css" rel="stylesheet" />
<script src="~/Admin/assets/js/daterangepicker/moment.min.js"></script>
<script src="~/Admin/assets/js/daterangepicker.js"></script>

DealSe/Areas/Admin/Views/Shared/_DatatableCSSJSView.cshtml
<link rel="stylesheet" type="text/css" href="~/admin/assets/css/datatablecss.css" />
<script src="~/admin/assets/js/datatablejs.js"></script>

DealSe/Areas/Admin/Views/Shared/_FillCommonDropdownListScript.cshtml
<script type="text/javascript">
    $("#CountryId").change(function () {
        var countryId = $(this).val();
        $("#StateId").val("");
        $("#StateId").html('<option value="">Select State</option>');
        $("#CityId").html('<option value="">Select City</option>');
        if (countryId == null || countryId == "") {
            $("#StateId").trigger('change');
            $("#CityId").trigger('change');
            return false;
        }
        $.ajax({
            url: '/Admin/FillCommonDropdownList/GetStateListByCountryId/',
            data: { countryId: countryId },
            success: function (result) {
                var items = '<option value="">Select State</option>';
                $.each(result, function (i, us) {
                    items += "<option value='" + us.value + "'>" + us.text + "</option>";
                });
                $('#StateId').html(items);
            },
            error: function (ex) {
                alert("Opps! Something went wrong.." + ex);
            },
        });
    });

    $("#StateId").change(function () {
        var stateId = $(this).val();
        $("#CityId").html('<option value="">Select City</option>');
        if (stateId == null || stateId == "") {
            $("#CityId").trigger('change');
            return false;
        }
        $.ajax({
            url: '/Admin/FillCommonDropdownList/GetCityListByStateId/',
            data: { stateId: stateId },
            success: function (result) {
                var items = '<option value="">Select City</option>';
                $.each(result, function (i, us) {
                    items += "<option value='" + us.value + "'>" + us.text + "</option>";
                });
                $('#CityId').html(items);
            },
            error: function (ex) {
                alert("Opps! Something went wrong.." + ex);
            },
        });
    });

    $("#CityId").change(function () {
        var cityId = $(this).val();
        $("#AreaId").html('<option value="">Select Area</option>');
        if (cityId == null || cityId == "") {
            $("#AreaId").trigger('change');
            return false;
        }
        $.ajax({
            url: '/Admin/FillCommonDropdownList/GetAreaListByCityId/',
            data: { cityId: cityId },
            success: function (result) {
                var items = '<option value="">Select City</option>';
                $.each(result, function (i, us) {
                    items += "<option value='" + us.value + "'>" + us.text + "</option>";
                });
                $('#AreaId').html(items);
            },
            error: function (ex) {
                alert("Opps! Something went wrong.." + ex);
            },
        });
    });
</script>

DealSe/Areas/Admin/Views/Shared/_Footer.cshtml
<footer class="main hidden-print">
    &copy; @DateTime.Now.Year <strong>DealSe.</strong>
</footer>

DealSe/Areas/Admin/Views/Shared/_Header.cshtml
@*Partial view for header*@
@using Microsoft.AspNetCore.Http
<div class="col-md-6 col-sm-8 clearfix" id="notification">
    <ul class="user-info pull-left pull-none-xsm">
        <li class="profile-info dropdown">
            <a href="#" class="dropdown-toggle profile-info-main" data-toggle="dropdown">
                @if (!string.IsNullOrEmpty(Context.Session.GetString("username")))
                {
                    <text> @Html.Raw(Context.Session.GetString("username"))</text>
                }
            </a>
            <ul class="dropdown-menu">
                <li class="caret"></li>
                <li>
                    <a asp-area="Admin" asp-controller="Home" asp-action="EditProfile">
                        <i class="entypo-user"></i>
                        Edit Profile
                    </a>
                </li>
            </ul>
        </li>
    </ul>
    <ul class="user-info pull-left pull-right-xs pull-none-xsm">
        <!-- Raw Notifications -->
        <li class="notifications dropdown open" id="notifications-dropdown-id">
        </li>
    </ul>
</div>
<!-- Raw Links -->
<div class="col-md-6 col-sm-4 clearfix">
    <ul class="list-inline links-list pull-right">
        <li style="padding-top:2px;">
            <a asp-area="admin" asp-controller="Home" asp-action="LogOff">
                <i class="entypo-logout right"></i>Log Out
            </a>
        </li>
    </ul>
</div>

DealSe/Areas/Admin/Views/Shared/_Layout.cshtml
@*Partial view for layout*@
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Neon Admin Panel" />
    <meta name="author" content="" />
    <title>DealSe</title>
    <link rel="stylesheet" href="/admin/assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css">
    <link rel="stylesheet" href="/admin/assets/css/font-icons/entypo/css/entypo.css">
    <link rel="stylesheet" href="/admin/assets/css/font-icons/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic">
    <link rel="stylesheet" href="/admin/assets/css/bootstrap.css">
    <link rel="stylesheet" href="/admin/assets/css/neon-core.css">
    <link rel="stylesheet" href="/admin/assets/css/neon-theme.css">
    <link rel="stylesheet" href="/admin/assets/css/neon-forms.css">
    <link rel="stylesheet" href="/admin/assets/css/custom.css">
    <link rel="stylesheet" href="/admin/assets/js/datatables/responsive/css/datatables.responsive.css">
    <link rel="stylesheet" href="/admin/assets/js/select2/select2-bootstrap.css">
    <link rel="stylesheet" href="/admin/assets/js/select2/select2.css">
    <link rel="stylesheet" href="/admin/assets/css/jquery-confirm.min.css">
    @RenderSection("styles", required: false)
    <script src="/admin/assets/js/jquery-1.11.0.min.js"></script>
    <script src="~/admin/assets/js/commonjs.js"></script>
</head>
<body class="page-body" data-url="http://neon.dev">
    <div class="page-container">
        @await Html.PartialAsync("_Sidebar")
        <div class="main-content">
            <div class="row">
                @await Html.PartialAsync("_Header")
            </div>
            <hr />
            <div id="preloader" class="loading" style="display:none"></div>
            @Html.Hidden("admin", Context.Session.GetString("admin"))
            @RenderBody()
            @await Html.PartialAsync("_Footer")
        </div>
    </div>
    <link rel="stylesheet" href="/admin/assets/js/jvectormap/jquery-jvectormap-1.2.2.css">
    <link rel="stylesheet" href="/admin/assets/js/rickshaw/rickshaw.min.css">
    <!-- Bottom Scripts -->
    <script src="/admin/assets/js/gsap/main-gsap.js"></script>
    <script src="/admin/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js"></script>
    <script src="/admin/assets/js/bootstrap.js"></script>
    <script src="/admin/assets/js/joinable.js"></script>
    <script src="/admin/assets/js/resizeable.js"></script>
    <script src="/admin/assets/js/neon-api.js"></script>
    <script src="~/admin/assets/js/jquery.inputmask.bundle.min.js"></script>
    <script src="/admin/assets/js/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/admin/assets/js/jvectormap/jquery-jvectormap-europe-merc-en.js"></script>
    <script src="/admin/assets/js/jquery.sparkline.min.js"></script>
    <script src="/admin/assets/js/rickshaw/vendor/d3.v3.js"></script>
    <script src="/admin/assets/js/rickshaw/rickshaw.min.js"></script>
    <script src="/admin/assets/js/raphael-min.js"></script>
    <script src="/admin/assets/js/morris.min.js"></script>
    <script src="/admin/assets/js/toastr.js"></script>
    <script src="/admin/assets/js/neon-chat.js"></script>
    <script src="/admin/assets/js/neon-custom.js"></script>
    <script src="/admin/assets/js/neon-demo.js"></script>
    <script src="/admin/assets/js/jquery.dataTables.min.js"></script>
    <script src="/admin/assets/js/datatables/TableTools.min.js"></script>
    <script src="/admin/assets/js/dataTables.bootstrap.js"></script>
    <script src="/admin/assets/js/datatables/jquery.dataTables.columnFilter.js"></script>
    <script src="/admin/assets/js/datatables/lodash.min.js"></script>
    <script src="/admin/assets/js/datatables/responsive/js/datatables.responsive.js"></script>
    <script src="/admin/assets/js/select2/select2.min.js"></script>
    <script src="/admin/assets/js/jquery-confirm.min.js"></script>
    <script src="~/Admin/assets/js/jquery.validate.min.js"></script>
    <script src="~/Admin/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/Admin/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>
<script src="/signalr/signalr.js"></script>
<script src="/Admin/js/adminnotification.js"></script>

DealSe/Areas/Admin/Views/Shared/_Sidebar.cshtml
@*Partial view for sidebar*@
<div class="sidebar-menu hidden-print">
    <header class="logo-env">
        <!-- logo -->
        <div class="logo">
            <a href="/Admin" style="font-size: 35px;color:dimgray">
                DealSe
            </a>
        </div>
        <!-- logo collapse icon -->
        <div class="sidebar-collapse" id="sidebar-collapse">
            <a href="javascript:void(0)" class="sidebar-collapse-icon with-animation">
                <i class="entypo-menu"></i>
            </a>
        </div>
        <div class="sidebar-mobile-menu visible-xs">
            <a href="#" class="with-animation">
                <i class="entypo-menu"></i>
            </a>
        </div>
    </header>
    <ul id="main-menu" class="">
        @*<li class="active opened active">*@
        <li id="lidashboard">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index">
                <i class="entypo-gauge"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li id="listoretype">
            <a asp-area="Admin" asp-controller="StoreType" asp-action="Index">
                <i class="entypo-home"></i>
                <span>Store Type</span>
            </a>
        </li>
        <li id="listore">
            <a asp-area="Admin" asp-controller="Store" asp-action="Index">
                <i class="entypo-home"></i>
                <span>Store</span>
            </a>
        </li>
        <li id="lioffer">
            <a asp-area="Admin" asp-controller="Offer" asp-action="Index">
                <i class="entypo-home"></i>
                <span>Offer</span>
            </a>
        </li>
        <li id="liothers">
            <a href="#"><i class="entypo-cog"></i><span>Others</span></a>
            <ul>
                <li id="licountry">
                    <a asp-area="Admin" asp-controller="Country" asp-action="Index">
                        <i class="entypo-globe"></i><span>Countries</span>
                    </a>
                </li>
                <li id="licountry">
                    <a asp-area="Admin" asp-controller="State" asp-action="Index">
                        <i class="entypo-globe"></i><span>States</span>
                    </a>
                </li>
                <li id="licountry">
                    <a asp-area="Admin" asp-controller="City" asp-action="Index">
                        <i class="entypo-globe"></i><span>Cities</span>
                    </a>
                </li>
                <li id="licountry">
                    <a asp-area="Admin" asp-controller="Area" asp-action="Index">
                        <i class="entypo-globe"></i><span>Areas</span>
                    </a>
                </li>
                <li id="liemailtemplate">
                    <a asp-area="Admin" asp-controller="EmailTemplate" asp-action="Index">
                        <i class="entypo-mail"></i><span>Email Templates</span>
                    </a>
                </li>
                <li id="lisitesetting">
                    <a asp-area="Admin" asp-controller="SiteSetting" asp-action="Index">
                        <i class="entypo-tools"></i><span>Site Settings</span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>